services:
  postgres:
    image: postgres:15-alpine
    container_name: nextflow_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: nextflow
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nextflow_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: