import type { Metadata } from "next";
import { TooltipProvider } from "@nextflow/ui";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0A0A0A]">
        <ClerkProvider
          appearance={{
            baseTheme: dark,
            variables: { colorPrimary: "#3b82f6" },
          }}
        >

          <TooltipProvider>
            <div className="flex min-h-0 min-w-0 flex-1 flex-col">{children}</div>
          </TooltipProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
